
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
/**
 * Returns Ok(path) if the MCP sidecar was found at startup, or Err(reason) if not.
 */
async getMcpStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickWorkflowFile() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_workflow_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickSaveFile() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_save_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(path: string) : Promise<Result<ProjectData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject(path: string, workflow: Workflow) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path, workflow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validate(workflow: Workflow) : Promise<ValidationResult> {
    return await TAURI_INVOKE("validate", { workflow });
},
async nodeTypeDefaults() : Promise<NodeTypeInfo[]> {
    return await TAURI_INVOKE("node_type_defaults");
},
async generateAutoId(nodeTypeName: string, countersJson: string) : Promise<Result<[string, string], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_auto_id", { nodeTypeName, countersJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runWorkflow(request: RunRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_workflow", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWorkflow() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_workflow") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supervisionRespond(action: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supervision_respond", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuns(query: RunsQuery) : Promise<Result<NodeRun[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadRunEvents(query: RunEventsQuery) : Promise<Result<TraceEvent[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_run_events", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readArtifactBase64(path: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_artifact_base64", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAsset(projectPath: string) : Promise<Result<ImportedAsset | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWalkthrough(workflowId: string, projectPath: string | null, supervisor: EndpointConfig | null, cdpApps: CdpAppConfig[], hoverDwellThreshold: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_walkthrough", { workflowId, projectPath, supervisor, cdpApps, hoverDwellThreshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWalkthrough(supervisor: EndpointConfig | null, hoverDwellThreshold: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_walkthrough", { supervisor, hoverDwellThreshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWalkthroughDraft() : Promise<Result<WalkthroughDraftResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_walkthrough_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyWalkthroughAnnotations(annotations: WalkthroughAnnotations) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_walkthrough_annotations", { annotations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedWalkthroughCache(workflowId: string, workflowName: string, projectPath: string | null, appEntries: AppResolutionSeedEntry[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_walkthrough_cache", { workflowId, workflowName, projectPath, appEntries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectCdpApps() : Promise<Result<DetectedCdpApp[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_cdp_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateAppPath(path: string) : Promise<Result<DetectedCdpApp, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_app_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChromeProfiles() : Promise<Result<ChromeProfile[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chrome_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChromeProfile(name: string) : Promise<Result<ChromeProfile, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chrome_profile", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isChromeProfileConfigured(profileId: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_chrome_profile_configured", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChromeProfilePath(profileId: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chrome_profile_path", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchChromeForSetup(profileId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_chrome_for_setup", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmableTools() : Promise<ConfirmableTool[]> {
    return await TAURI_INVOKE("confirmable_tools");
},
async checkEndpoint(baseUrl: string, apiKey: string | null, model: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_endpoint", { baseUrl, apiKey, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels(baseUrl: string, apiKey: string | null) : Promise<Result<string[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models", { baseUrl, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runAgent(request: AgentRunRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_agent", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAgent() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async approveAgentAction(approved: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_agent_action", { approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a pending VLM completion disagreement. The operator picks
 * either `confirm` (override the VLM, mark the run complete) or
 * `cancel` (agree with the VLM, halt the run). The backend records the
 * decision to `events.jsonl` + `variant_index.jsonl` and emits the
 * appropriate terminal Tauri event.
 * 
 * Concurrency note: the AgentHandle lock is held across the oneshot
 * send on purpose. `force_stop` (the Stop button) also locks the
 * AgentHandle, cancels the run's CancellationToken, and takes the
 * disagreement sender from the same slot. If this command released
 * the lock after `.take()` but before `.send()`, a concurrent
 * `force_stop` could trip the cancel token in the gap and the
 * `tokio::select!` in `await_disagreement_resolution` would pick the
 * cancel branch before the confirm ever arrived — silently losing
 * the operator's decision. `oneshot::Sender::send` is synchronous
 * and infallible except for a dropped receiver, so holding the
 * `std::sync::Mutex` across it is cheap and race-closing.
 */
async resolveCompletionDisagreement(action: CompletionDisagreementActionWire) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_completion_disagreement", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadAgentChat(request: LoadAgentChatRequest) : Promise<Result<AgentChat, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_agent_chat", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAgentChat(request: SaveAgentChatRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_agent_chat", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pruneAgentCacheForNodes(request: PruneAgentCacheRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prune_agent_cache_for_nodes", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAgentConversation(request: ClearAgentConversationRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_agent_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionConfidence = "High" | "Medium" | "Low"
/**
 * Persisted transcript — a sibling file to `agent_cache.json`.
 * Kept deliberately minimal (no schema version) until the format
 * changes; versioning is added lazily when it matters.
 */
export type AgentChat = { messages: AgentChatMessage[] }
export type AgentChatMessage = { role: AgentChatRole; content: string; timestamp: string; run_id?: string | null }
export type AgentChatRole = "user" | "assistant" | "system"
export type AgentRunRequest = { goal: string; agent: EndpointConfig; project_path: string | null; workflow_name: string; workflow_id: string; 
/**
 * Permission policy for this run. When `None`, the default policy
 * (empty rules, allow_all=false, guardrail off) is used.
 */
permissions?: PermissionPolicyWire | null; 
/**
 * Halt the run after this many consecutive destructive tool calls.
 * `0` disables the cap. `None` uses the engine default (3).
 */
consecutive_destructive_cap?: number | null;
/**
 * Permit `focus_window` MCP calls. When `Some(false)` the runner
 * suppresses every `focus_window` call with a synthetic skip,
 * regardless of app kind or CDP state — useful for background-run
 * policies. `None` leaves the engine default (`true`) in place.
 */
allow_focus_window?: boolean | null;
/**
 * Privacy kill switch: when false, the run is entirely in-memory.
 * No `.clickweave/runs/` directory is created and no trace files
 * or cache files are written. When `None`, persistence is on —
 * matches the UI default (`storeTraces: true`).
 */
store_traces?: boolean | null; 
/**
 * Frontend-generated run ID. The engine stamps every node built
 * this run with this ID, and `agent://*` events echo it back.
 * When omitted (legacy callers / tests), a UUID is generated here.
 */
run_id?: string | null; 
/**
 * Anchor node to seed `last_node_id` from. When present, the
 * run's first emitted edge is from `anchor_node_id` to whatever
 * first node the agent builds.
 */
anchor_node_id?: string | null; 
/**
 * Prior conversation turns (goal + summary + run_id) injected
 * inline above the current goal. Runtime order = chronological.
 */
prior_turns?: PriorTurnWire[];
/**
 * Spec 2 master kill switch for episodic memory on this run.
 * `None` = inherit the engine default (`true`); `Some(false)` =
 * run with episodic disabled regardless of `EpisodicContext`.
 */
episodic_enabled?: boolean | null;
/**
 * Spec 2 retrieval depth — top-k episodes returned per trigger.
 * `None` = engine default (2). Clamped to `[1, 10]` at the
 * Tauri seam.
 */
retrieved_episodes_k?: number | null;
/**
 * Spec 2 D35 privacy opt-in: when `true`, recoveries from this
 * workflow may be promoted into the global cross-workflow store.
 * Default off keeps workflows isolated.
 */
episodic_global_participation?: boolean | null }
export type AiStepParams = { prompt: string; button_text: string | null; template_image: string | null; max_tool_calls: number | null; allowed_tools: string[] | null; timeout_ms?: number | null }
export type AppDebugKitParams = { operation_name: string; parameters: JsonValue }
/**
 * Classification of an app's UI framework, used to decide whether
 * Chrome DevTools Protocol (CDP) tools can provide better automation.
 * 
 * - `Native`: standard native app — use accessibility-based automation
 * - `ChromeBrowser`: Chrome-family browser — CDP gives DOM access
 * - `ElectronApp`: Electron-based app — native AX is unreliable, CDP preferred
 */
export type AppKind = "Native" | "ChromeBrowser" | "ElectronApp"
export type AppResolutionSeedEntry = { node_id: string; app_name: string }
export type Artifact = { artifact_id: string; kind: ArtifactKind; path: string; metadata: JsonValue; overlays: JsonValue[] }
export type ArtifactKind = "Screenshot" | 
/**
 * Catch-all for any artifact that doesn't fit a more specific category.
 * Legacy kinds (`Ocr`, `TemplateMatch`, `Log`) were never produced —
 * `#[serde(other)]` lets pre-removal artifact records still deserialize.
 */
"Other"
export type AxClickParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: AxTarget }
export type AxSelectParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: AxTarget }
export type AxSetValueParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: AxTarget; value: string }
/**
 * Distinguishes how a macOS accessibility-tree element target was produced,
 * so the executor can choose the right resolution strategy at dispatch time.
 * 
 * AX snapshots are session-stateful: every call to `take_ax_snapshot` bumps a
 * generation and emits uids like `a42g3`. Uids from prior snapshots are
 * rejected by `ax_click` / `ax_set_value` / `ax_select` with
 * `snapshot_expired`. To replay safely, the executor re-snapshots immediately
 * before each dispatch and resolves the node's descriptor (role + name) to a
 * fresh uid — see [`clickweave_engine::executor::deterministic::ax`].
 */
export type AxTarget = 
/**
 * Replay-stable descriptor. Executor re-resolves via `take_ax_snapshot`
 * and matches the first entry with this `role` whose `name` matches —
 * optional `parent_name` breaks ties for sidebars/outlines where many
 * rows share a role.
 */
{ kind: "Descriptor"; value: { role: string; name: string; parent_name?: string | null } } | 
/**
 * Raw uid captured at agent run time. Valid only for the current AX
 * snapshot generation — will fail with `snapshot_expired` on replay.
 * Agent-loop post-hooks upgrade `ResolvedUid` to `Descriptor` when the
 * original snapshot is still on hand.
 */
{ kind: "ResolvedUid"; value: string }
/**
 * User-selected app for CDP during walkthrough.
 */
export type CdpAppConfig = { name: string; 
/**
 * Path to the app binary (from file picker). None for already-running apps.
 */
binary_path: string | null; app_kind: AppKind }
export type CdpClickParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: CdpTarget }
export type CdpClosePageParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { page_index?: number | null }
export type CdpFillParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: CdpTarget; value: string }
export type CdpHandleDialogParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { accept: boolean; prompt_text?: string | null }
export type CdpHoverParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target: CdpTarget }
export type CdpNavigateParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { url: string }
export type CdpNewPageParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { url?: string }
export type CdpPressKeyParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { key: string; modifiers?: string[] }
export type CdpSelectPageParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { page_index: number }
/**
 * Distinguishes how a CDP element target was produced, so the executor can
 * choose the right resolution strategy.
 */
export type CdpTarget = 
/**
 * Precise element name from `cdp_find_elements` or walkthrough recording.
 */
{ kind: "ExactLabel"; value: string } | 
/**
 * Semantic description (e.g. "the message input field") — always resolved
 * via snapshot + LLM at execution time.
 */
{ kind: "Intent"; value: string } | 
/**
 * Concrete DOM UID resolved at execution time (for Run mode / decision cache).
 */
{ kind: "ResolvedUid"; value: string }
export type CdpTypeParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { text: string }
export type CdpWaitParams = { text: string; timeout_ms?: number }
export type ChromeProfile = { id: string; name: string; google_email: string | null }
export type ClearAgentConversationRequest = { project_path: string | null; workflow_name: string; workflow_id: string; store_traces: boolean }
export type ClickParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target?: ClickTarget | null; button: MouseButton; click_count: number }
export type ClickTarget = { type: "Text"; text: string } | { type: "Coordinates"; x: number; y: number } | { type: "WindowControl"; action: WindowControlAction }
/**
 * Structured error type for Tauri IPC commands.
 */
export type CommandError = { kind: ErrorKind; message: string }
/**
 * Wire form for `resolve_completion_disagreement`. Mirrors
 * `DisagreementResolutionAction` but derives `specta::Type` so the
 * TypeScript binding picks it up.
 */
export type CompletionDisagreementActionWire = "confirm" | "cancel"
export type ConfirmableTool = { name: string; description: string }
/**
 * A running app detected as Electron or Chrome, returned to the frontend for CDP selection.
 */
export type DetectedCdpApp = { name: string; pid: number; app_kind: AppKind }
export type DragParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { from_x?: number | null; from_y?: number | null; to_x?: number | null; to_y?: number | null }
export type Edge = { from: string; to: string }
export type EndpointConfig = { base_url: string; model: string; api_key: string | null }
export type ErrorKind = "Validation" | "Io" | "Mcp" | "AlreadyRunning" | "Internal"
export type ExecutionMode = "Test" | "Run"
export type FindAppParams = { search: string }
export type FindImageParams = { template_image: string | null; threshold: number; max_results: number }
export type FindTextParams = { search_text?: string; scope?: string | null }
export type FocusWindowParams = ({ method: "AppName"; value: string } | { method: "WindowId"; value: number } | { method: "Pid"; value: number }) & ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { bring_to_front: boolean; app_kind?: AppKind; chrome_profile_id?: string | null }
export type HoverParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { target?: ClickTarget | null; dwell_ms: number }
export type ImportedAsset = { relative_path: string; absolute_path: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LaunchAppParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { app_name: string }
export type LoadAgentChatRequest = { project_path: string | null; workflow_name: string; workflow_id: string }
export type McpToolCallParams = { tool_name: string; arguments: JsonValue }
export type MouseButton = "Left" | "Right" | "Center"
export type Node = { id: string; node_type: NodeType; position: Position; name: string; description?: string | null; auto_id?: string; enabled: boolean; timeout_ms: number | null; settle_ms: number | null; retries: number; supervision_retries?: number; trace_level: TraceLevel; role?: NodeRole; expected_outcome: string | null; 
/**
 * Provenance stamp: the agent generation ID that produced this node.
 * `None` for nodes added by the user, by deterministic walkthrough
 * synthesis, or loaded from a pre-upgrade workflow file. Used by
 * Clear-conversation and selective-delete to scope operations to
 * agent-built nodes only.
 */
source_run_id?: string | null }
export type NodeGroup = { id: string; name: string; color: string; node_ids: string[]; parent_group_id: string | null }
export type NodeRename = { node_id: string; new_name: string }
export type NodeRole = "Default" | "Verification"
export type NodeRun = { run_id: string; node_id: string; node_name?: string; execution_dir?: string; started_at: number; ended_at: number | null; status: RunStatus; trace_level: TraceLevel; events: TraceEvent[]; artifacts: Artifact[]; observed_summary: string | null }
export type NodeType = ({ type: "FindText" } & FindTextParams) | ({ type: "FindImage" } & FindImageParams) | ({ type: "FindApp" } & FindAppParams) | ({ type: "TakeScreenshot" } & TakeScreenshotParams) | ({ type: "Click" } & ClickParams) | ({ type: "Hover" } & HoverParams) | ({ type: "Drag" } & DragParams) | ({ type: "TypeText" } & TypeTextParams) | ({ type: "PressKey" } & PressKeyParams) | ({ type: "Scroll" } & ScrollParams) | ({ type: "FocusWindow" } & FocusWindowParams) | ({ type: "LaunchApp" } & LaunchAppParams) | ({ type: "QuitApp" } & QuitAppParams) | ({ type: "CdpWait" } & CdpWaitParams) | ({ type: "CdpClick" } & CdpClickParams) | ({ type: "CdpHover" } & CdpHoverParams) | ({ type: "CdpFill" } & CdpFillParams) | ({ type: "CdpType" } & CdpTypeParams) | ({ type: "CdpPressKey" } & CdpPressKeyParams) | ({ type: "CdpNavigate" } & CdpNavigateParams) | ({ type: "CdpNewPage" } & CdpNewPageParams) | ({ type: "CdpClosePage" } & CdpClosePageParams) | ({ type: "CdpSelectPage" } & CdpSelectPageParams) | ({ type: "CdpHandleDialog" } & CdpHandleDialogParams) | ({ type: "AxClick" } & AxClickParams) | ({ type: "AxSetValue" } & AxSetValueParams) | ({ type: "AxSelect" } & AxSelectParams) | ({ type: "AiStep" } & AiStepParams) | ({ type: "McpToolCall" } & McpToolCallParams) | ({ type: "AppDebugKitOp" } & AppDebugKitParams) | 
/**
 * Placeholder for removed or unrecognized node types. Preserved on
 * load so that old workflows don't hard-fail; the UI can display them
 * as disabled/unsupported.
 */
{ type: "Unknown" }
export type NodeTypeInfo = { name: string; output_role: string; node_context: string; icon: string; node_type: NodeType }
export type PermissionActionWire = "allow" | "ask" | "deny"
/**
 * Wire form of the permission policy the UI ships with every `run_agent`.
 * `tools` is the per-tool override map from the existing 2-tier UI (ask
 * / allow). It is mapped into `PermissionRule`s with the tool name as a
 * literal pattern so the Rust side only needs one evaluator.
 */
export type PermissionPolicyWire = { rules?: PermissionRuleWire[]; allow_all?: boolean; require_confirm_destructive?: boolean; 
/**
 * Per-tool overrides: `{ "click": "allow" }`. Merged into the rule
 * list as literal-pattern rules before the evaluator runs.
 */
per_tool?: Partial<{ [key in string]: PermissionActionWire }> }
/**
 * Wire form of a single permission rule. Mirrors
 * `clickweave_engine::agent::PermissionRule` but with a `specta::Type`
 * derive so the TypeScript bindings pick it up.
 */
export type PermissionRuleWire = { tool_pattern: string; args_pattern: string | null; action: PermissionActionWire }
export type Position = { x: number; y: number }
export type PressKeyParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { key: string; modifiers?: string[] }
/**
 * Wire form of a prior-turn entry (matches
 * `clickweave_engine::agent::PriorTurn` with string UUIDs for JSON).
 */
export type PriorTurnWire = { goal: string; summary: string; run_id: string }
export type ProjectData = { path: string; workflow: Workflow }
export type PruneAgentCacheRequest = { project_path: string | null; workflow_name: string; workflow_id: string; node_ids: string[]; store_traces: boolean }
export type QuitAppParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { app_name: string }
export type RunEventsQuery = { project_path: string | null; workflow_id: string; workflow_name: string; node_name: string; execution_dir: string | null; run_id: string }
export type RunRequest = { workflow: Workflow; project_path: string | null; agent: EndpointConfig; fast: EndpointConfig | null; 
/**
 * Supervisor LLM used for step verdict in Test mode.
 */
supervisor: EndpointConfig | null; execution_mode: ExecutionMode; supervision_delay_ms?: number; 
/**
 * Privacy kill switch: when false, the run is entirely in-memory
 * and no files are written under `.clickweave/runs/`. When missing,
 * persistence is on — matches the UI default (`storeTraces: true`).
 */
store_traces?: boolean | null }
export type RunStatus = "Ok" | "Failed" | "Stopped" | "Cancelled"
export type RunsQuery = { project_path: string | null; workflow_id: string; workflow_name: string; node_name: string }
export type SaveAgentChatRequest = { project_path: string | null; workflow_name: string; workflow_id: string; chat: AgentChat; store_traces: boolean }
/**
 * Screenshot coordinate metadata for mapping screen coordinates to image pixels.
 * 
 * Given a screen coordinate `(sx, sy)`, the image pixel coordinate is:
 * `px = (sx - origin_x) * scale`, `py = (sy - origin_y) * scale`
 */
export type ScreenshotMeta = { origin_x: number; origin_y: number; scale: number }
export type ScreenshotMode = "Screen" | "Window" | "Region"
export type ScrollParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { delta_y: number; x?: number | null; y?: number | null }
export type TakeScreenshotParams = { mode: ScreenshotMode; target: string | null; include_ocr: boolean }
export type TargetCandidate = { type: "AccessibilityLabel"; label: string; role: string | null } | 
/**
 * Label identified by a vision language model from a screenshot crop.
 */
{ type: "VlmLabel"; label: string } | { type: "OcrText"; text: string } | { type: "ImageCrop"; path: string; image_b64: string } | { type: "Coordinates"; x: number; y: number } | 
/**
 * Element captured via Chrome DevTools Protocol click listener.
 */
{ type: "CdpElement"; name: string; role: string | null; href: string | null; parent_role: string | null; parent_name: string | null } | 
/**
 * macOS accessibility element reached via the native AX tree — the
 * target descriptor for `ax_click` / `ax_set_value` / `ax_select`.
 * Populated only when the role is actionable (button, text field,
 * menu item, row, etc.) and the app exposes an AX tree. Replay
 * re-resolves this to a fresh uid via `take_ax_snapshot` at
 * execution time, so no generation-tagged uid is carried on the
 * candidate.
 */
{ type: "AxElement"; role: string; name: string; parent_name?: string | null } | 
/**
 * macOS window control button (close, minimize, maximize).
 * Resolved at execution time to a window-relative click.
 */
{ type: "WindowControl"; action: WindowControlAction }
export type TargetOverride = { node_id: string; chosen_candidate_index: number }
export type TraceEvent = { timestamp: number; event_type: TraceEventKind; payload: JsonValue }
/**
 * The canonical set of trace event kinds emitted by the executor.
 * 
 * Serialized as snake_case strings so the on-disk shape matches the literal
 * event-type strings that the engine has emitted historically. Legacy
 * `events.jsonl` files therefore load unchanged. Unknown strings deserialize
 * as [`TraceEventKind::Unknown`] so forward-compatible additions don't break
 * old readers.
 */
export type TraceEventKind = "node_started" | "tool_call" | "tool_result" | "step_completed" | "step_failed" | "branch_evaluated" | "loop_iteration" | "target_resolved" | "action_verification" | "ambiguity_resolved" | "element_resolved" | "match_disambiguated" | "app_resolved" | "cdp_connected" | "cdp_click" | "cdp_hover" | "cdp_fill" | "ax_click" | "ax_set_value" | "ax_select" | "vision_summary" | "variable_set" | "retry" | "supervision_retry" | 
/**
 * Forward-compatibility catch-all for event kinds that aren't in this
 * enum yet. `#[serde(other)]` parses any unknown string into `Unknown`.
 */
"unknown"
export type TraceLevel = "Off" | "Minimal" | "Full"
export type TypeTextParams = ({ verification_method?: VerificationMethod | null; verification_assertion?: string | null }) & { text: string }
export type ValidationResult = { valid: boolean; errors: string[] }
export type VariablePromotion = { node_id: string; variable_name: string }
/**
 * Method used to verify an action node's effect.
 */
export type VerificationMethod = "Vlm" | "Dom" | "AccessibilityTree"
export type WalkthroughAction = { id: string; kind: WalkthroughActionKind; app_name: string | null; window_title: string | null; target_candidates: TargetCandidate[]; artifact_paths: string[]; source_event_ids: string[]; confidence: ActionConfidence; warnings: string[]; 
/**
 * Screenshot coordinate metadata for VLM click target resolution.
 */
screenshot_meta?: ScreenshotMeta | null; 
/**
 * Whether this action is a candidate (e.g. detected hover) that needs
 * explicit user confirmation before inclusion in the draft.
 */
candidate?: boolean }
export type WalkthroughActionKind = { type: "LaunchApp"; app_name: string; app_kind: AppKind } | { type: "FocusWindow"; app_name: string; window_title: string | null; app_kind: AppKind } | { type: "Click"; x: number; y: number; button: MouseButton; click_count: number } | { type: "TypeText"; text: string } | { type: "PressKey"; key: string; modifiers: string[] } | { type: "Scroll"; delta_y: number } | { type: "Hover"; x: number; y: number; dwell_ms: number }
export type WalkthroughAnnotations = { deleted_node_ids: string[]; renamed_nodes: NodeRename[]; target_overrides: TargetOverride[]; variable_promotions: VariablePromotion[] }
export type WalkthroughDraftResponse = { actions: WalkthroughAction[]; draft: Workflow | null; warnings: string[] }
/**
 * macOS window control button (traffic light) actions.
 * 
 * At execution time these are resolved to window-relative clicks by
 * querying the focused window's position and applying a fixed pixel offset.
 * This is more reliable than keyboard shortcuts — e.g. Cmd+W closes a tab
 * in tabbed apps, not the window.
 */
export type WindowControlAction = "Close" | "Minimize" | "Maximize" | 
/**
 * Green button in "zoom" mode — resizes/maximizes the window without
 * entering full screen. Same physical button as Maximize but different
 * macOS subrole (`AXZoomButton` vs `AXFullScreenButton`).
 */
"Zoom"
export type Workflow = { id: string; name: string; nodes: Node[]; edges: Edge[]; groups?: NodeGroup[]; next_id_counters?: Partial<{ [key in string]: number }>; intent?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
