
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
/**
 * Returns Ok(path) if the MCP sidecar was found at startup, or Err(reason) if not.
 */
async getMcpStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickWorkflowFile() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_workflow_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickSaveFile() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_save_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the slim [`ProjectManifest`] from `path`.
 * 
 * Pre-1.0 (D33): legacy `Workflow`-shaped envelopes are **not**
 * auto-migrated. If the JSON parses but contains the legacy graph
 * keys (`nodes`, `edges`), the loader returns a typed validation
 * error so the UI can surface a "start a new project" hint without
 * corrupting the file by overwriting it on the next save.
 */
async openProject(path: string) : Promise<Result<ProjectData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject(path: string, manifest: ProjectManifest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path, manifest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch a skill run via the native `skill_runner` (D28).
 * 
 * Resolves the requested skill from the project's `SkillStore`,
 * creates a per-run record under `<skills>/<skill_id>/runs/`, spawns
 * the MCP sidecar, and runs `run_skill_steps` against the skill's
 * `action_sketch`. Per-step events flow through the `ExecutorEvent`
 * channel and out to the UI via `executor://*` topics, mirroring the
 * shape used by the deleted `WorkflowExecutor`.
 */
async runSkill(request: RunSkillRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a skill run from a specific section after a failure.
 * 
 * Loads the skill's section list, collects the step IDs for every section
 * at or after `from_section_id`, and then runs only those steps. Sections
 * before `from_section_id` are skipped entirely.
 */
async resumeSkillFromFailure(request: ResumeSkillFromFailureRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_skill_from_failure", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWorkflow() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_workflow") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supervisionRespond(action: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supervision_respond", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List historical runs for a skill (D27).
 * 
 * When `query.run_id` is `Some`, the result contains at most a single
 * matching record (or empty when the run cannot be found). When
 * `None`, every persisted run for the skill is returned, sorted
 * oldest-first by `started_at`. The legacy node-keyed result shape
 * no longer exists — every run is keyed on `skill_id` per D28.
 */
async listRuns(query: RunsQuery) : Promise<Result<SkillRun[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the trace event log for a single skill run (D28).
 */
async loadRunEvents(query: RunEventsQuery) : Promise<Result<TraceEvent[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_run_events", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a base64-encoded artifact file from a skill run's per-run
 * directory.
 * 
 * The artifact path is sandboxed under `<run_id>/artifacts/` so a
 * caller cannot escape outside the directory tree even with absolute
 * or `..`-prefixed inputs. The shape of this command is unchanged
 * from the legacy node-keyed surface — only the run-locator fields
 * (`skill_id` + `run_id`) are skill-keyed.
 */
async readArtifactBase64(query: ReadArtifactQuery) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_artifact_base64", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAsset(projectPath: string) : Promise<Result<ImportedAsset | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWalkthrough(projectId: string, projectPath: string | null, supervisor: EndpointConfig | null, cdpApps: CdpAppConfig[], hoverDwellThreshold: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_walkthrough", { projectId, projectPath, supervisor, cdpApps, hoverDwellThreshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWalkthrough(supervisor: EndpointConfig | null, hoverDwellThreshold: number | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_walkthrough", { supervisor, hoverDwellThreshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelWalkthrough() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_walkthrough") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWalkthroughDraft() : Promise<Result<WalkthroughDraftResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_walkthrough_draft") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyWalkthroughAnnotations(annotations: WalkthroughAnnotations) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_walkthrough_annotations", { annotations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedWalkthroughCache(projectId: string, projectName: string, projectPath: string | null, appEntries: AppResolutionSeedEntry[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_walkthrough_cache", { projectId, projectName, projectPath, appEntries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWalkthroughAsSkill(request: SaveWalkthroughAsSkillRequest) : Promise<Result<Skill, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_walkthrough_as_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectCdpApps() : Promise<Result<DetectedCdpApp[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_cdp_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateAppPath(path: string) : Promise<Result<DetectedCdpApp, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_app_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChromeProfiles() : Promise<Result<ChromeProfile[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chrome_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChromeProfile(name: string) : Promise<Result<ChromeProfile, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chrome_profile", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isChromeProfileConfigured(profileId: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_chrome_profile_configured", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChromeProfilePath(profileId: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chrome_profile_path", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchChromeForSetup(profileId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_chrome_for_setup", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmableTools() : Promise<ConfirmableTool[]> {
    return await TAURI_INVOKE("confirmable_tools");
},
async checkEndpoint(baseUrl: string, apiKey: string | null, model: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_endpoint", { baseUrl, apiKey, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels(baseUrl: string, apiKey: string | null) : Promise<Result<string[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models", { baseUrl, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runAgent(request: AgentRunRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_agent", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAgent() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async approveAgentAction(approved: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_agent_action", { approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a pending VLM completion disagreement. The operator picks
 * either `confirm` (override the VLM, mark the run complete) or
 * `cancel` (agree with the VLM, halt the run). The backend records the
 * decision to `events.jsonl` + `variant_index.jsonl` and emits the
 * appropriate terminal Tauri event.
 * 
 * Concurrency note: the AgentHandle lock is held across the oneshot
 * send on purpose. `force_stop` (the Stop button) also locks the
 * AgentHandle, cancels the run's CancellationToken, and takes the
 * disagreement sender from the same slot. If this command released
 * the lock after `.take()` but before `.send()`, a concurrent
 * `force_stop` could trip the cancel token in the gap and the
 * `tokio::select!` in `await_disagreement_resolution` would pick the
 * cancel branch before the confirm ever arrived — silently losing
 * the operator's decision. `oneshot::Sender::send` is synchronous
 * and infallible except for a dropped receiver, so holding the
 * `std::sync::Mutex` across it is cheap and race-closing.
 */
async resolveCompletionDisagreement(action: CompletionDisagreementActionWire) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_completion_disagreement", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the current agent run as a new skill. The run's tool calls are
 * converted to `ActionSketchStep[]`, prose is generated, and the skill
 * is written to the project's skill store.
 */
async saveRunAsSkill(request: SaveRunAsSkillRequest) : Promise<Result<Skill, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_run_as_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Append the current agent run's steps to an existing skill as a new
 * section. Reads the existing SKILL.md, appends the new steps, and
 * writes the updated file at an incremented version.
 */
async addRunToSkill(request: AddRunToSkillRequest) : Promise<Result<Skill, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_run_to_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadAgentChat(request: LoadAgentChatRequest) : Promise<Result<AgentChat, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_agent_chat", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAgentChat(request: SaveAgentChatRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_agent_chat", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pruneSkillLineageForNodes(request: PruneSkillLineageRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prune_skill_lineage_for_nodes", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAgentConversation(request: ClearAgentConversationRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_agent_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmSkillProposal(request: ConfirmSkillProposalRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_skill_proposal", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rejectSkillProposal(request: RejectSkillProposalRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_skill_proposal", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async promoteSkillToGlobal(request: PromoteSkillToGlobalRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("promote_skill_to_global", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forkSkill(request: ForkSkillRequest) : Promise<Result<Skill, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fork_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSkill(request: DeleteSkillRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillsForPanel(request: ListSkillsRequest) : Promise<Result<SkillSummary[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills_for_panel", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the full [`Skill`] value (including `sections`, `body`, and
 * `action_sketch`) for a given `(skill_id, version)` pair from the
 * project-local skill directory. Versions are resolved by reading
 * `<skill_id>/SKILL.md` and matching against the requested version.
 */
async loadSkillFull(request: LoadSkillFullRequest) : Promise<Result<Skill, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_skill_full", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a four-layer `SkillPatch` atomically to a skill's on-disk files.
 * 
 * Steps:
 * 1. Resolve the project skills directory.
 * 2. Read the current `SKILL.md` (and optional `replay.json` sidecar).
 * 3. Validate the `expected_mtime_ms` guard against the current file mtime.
 * 4. Apply the patch in-memory (pure).
 * 5. Run structural lint; reject with lint errors before opening the journal.
 * 6. Emit post-patch byte buffers.
 * 7. Write via `SkillStore::write_atomic_multi_file` (journal protocol).
 */
async applySkillPatch(request: ApplySkillPatchRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_skill_patch", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadLatestRunTrace(request: LoadLatestRunTraceRequest) : Promise<Result<HydratedRunTrace | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_latest_run_trace", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionConfidence = "High" | "Medium" | "Low"
/**
 * Wire-format `ActionSketchReplacement` for Tauri IPC.
 */
export type ActionSketchReplacementDto = { step_id: string; field: string; new_value: JsonValue }
export type ActionSketchStep = { type: "tool_call"; step_id: string; tool: string; args: JsonValue; captures_pre: CaptureClause[]; captures: CaptureClause[]; expected_world_model_delta: ExpectedWorldModelDelta; requires_approval?: boolean | null } | { type: "loop"; step_id: string; until: LoopPredicate; body: ActionSketchStep[]; max_iterations: number; iteration_delay_ms: number }
export type AddRunToSkillRequest = { project_path: string | null; project_name: string; project_id: string; skill_id: string; version: number; goal: string; steps: AgentStepWire[]; store_traces: boolean }
/**
 * Persisted transcript — a sibling file to the workflow run metadata.
 * Kept deliberately minimal (no schema version) until the format
 * changes; versioning is added lazily when it matters.
 */
export type AgentChat = { messages: AgentChatMessage[] }
export type AgentChatMessage = { role: AgentChatRole; content: string; timestamp: string; run_id?: string | null }
export type AgentChatRole = "user" | "assistant" | "system"
export type AgentRunRequest = { goal: string; agent: EndpointConfig; project_path: string | null; project_name: string; project_id: string; 
/**
 * Permission policy for this run. When `None`, the default policy
 * (empty rules, allow_all=false, guardrail off) is used.
 */
permissions?: PermissionPolicyWire | null; 
/**
 * Halt the run after this many consecutive destructive tool calls.
 * `0` disables the cap. `None` uses the engine default (3).
 */
consecutive_destructive_cap?: number | null; 
/**
 * Permit `focus_window` MCP calls. When `Some(false)` the runner
 * suppresses every `focus_window` call with a synthetic skip
 * regardless of app kind or CDP state. When `Some(true)` the
 * runner permits `focus_window` and the AX/CDP-scoped guards in
 * `runner.rs` decide per-call whether the focus is redundant.
 * `None` leaves the engine default (`false`) in place — runs
 * operate in the background unless explicitly opted in.
 */
allow_focus_window?: boolean | null; 
/**
 * Privacy kill switch: when false, the run is entirely in-memory.
 * No `.clickweave/runs/` directory is created and no trace files
 * or agent metadata files are written. When `None`, persistence is on —
 * matches the UI default (`storeTraces: true`).
 */
store_traces?: boolean | null; 
/**
 * Frontend-generated run ID. The engine stamps every node built
 * this run with this ID, and `agent://*` events echo it back.
 * When omitted (legacy callers / tests), a UUID is generated here.
 */
run_id?: string | null; 
/**
 * Anchor node to seed `last_node_id` from. When present, the
 * run's first emitted edge is from `anchor_node_id` to whatever
 * first node the agent builds.
 */
anchor_node_id?: string | null; 
/**
 * Prior conversation turns (goal + summary + run_id) injected
 * inline above the current goal. Runtime order = chronological.
 */
prior_turns?: PriorTurnWire[]; 
/**
 * Spec 2 master kill switch for episodic memory on this run.
 * `None` = inherit the engine default (`true`); `Some(false)` =
 * run with episodic disabled regardless of `EpisodicContext`.
 */
episodic_enabled?: boolean | null; 
/**
 * Spec 2 retrieval depth — top-k episodes returned per trigger.
 * `None` = engine default (2). Clamped to `[1, 10]` at the
 * Tauri seam.
 */
retrieved_episodes_k?: number | null; 
/**
 * Spec 2 D35 privacy opt-in: when `true`, recoveries from this
 * workflow may be promoted into the global cross-workflow store.
 * Default off keeps workflows isolated.
 */
episodic_global_participation?: boolean | null; 
/**
 * Spec 3 master kill switch for procedural skills on this run.
 * `None` = inherit the engine default (`true`); `Some(false)` =
 * run with skill extraction/retrieval/replay disabled.
 */
skills_enabled?: boolean | null; 
/**
 * Spec 3 retrieval depth — top-k applicable skills returned per
 * `push_subgoal` boundary. Clamped to `[1, 10]` at the Tauri seam.
 */
applicable_skills_k?: number | null; 
/**
 * Spec 3 privacy opt-in: when `true`, confirmed global skills may
 * participate in retrieval for this run.
 */
skills_global_participation?: boolean | null }
/**
 * One agent step sent from the frontend for skill materialisation.
 * `args_json` is the JSON-serialised tool arguments; empty string is
 * treated the same as `{}`.
 */
export type AgentStepWire = { summary: string; tool_name: string; args_json: string }
/**
 * Classification of an app's UI framework, used to decide whether
 * Chrome DevTools Protocol (CDP) tools can provide better automation.
 * 
 * - `Native`: standard native app — use accessibility-based automation
 * - `ChromeBrowser`: Chrome-family browser — CDP gives DOM access
 * - `ElectronApp`: Electron-based app — native AX is unreliable, CDP preferred
 */
export type AppKind = "Native" | "ChromeBrowser" | "ElectronApp"
export type AppResolutionSeedEntry = { node_id: string; app_name: string }
export type ApplicabilityHints = { apps: string[]; hosts: string[]; signature: ApplicabilitySignature }
export type ApplicabilitySignature = string
/**
 * Request body for [`apply_skill_patch`].
 */
export type ApplySkillPatchRequest = { skill_id: string; version: number; 
/**
 * If `Some`, the current SKILL.md's mtime (millis since Unix epoch) must
 * match this value or the command returns `ExternalConflict`.
 */
expected_mtime_ms: number | null; markdown_replacements: MarkdownReplacementDto[]; action_sketch_replacements: ActionSketchReplacementDto[]; variables_additions: SkillFrontmatterVariableDto[]; replay_sidecar_mutations: ReplaySidecarMutationDto[]; primitive: SkillPatchPrimitiveDto; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
export type AxDescriptorMatch = { role: string; name: string; parent_name: string | null }
export type BindingCorrection = { step_index: number; capture_name: string; keep: boolean; correction: CaptureClause | null }
export type BindingRef = { type: "captured"; name: string } | { type: "params"; name: string }
export type BoundaryKind = "terminal" | "subgoal_completed" | "recovery_succeeded"
export type CaptureClause = { name: string; source: CaptureSource }
export type CaptureSource = { type: "ax_descriptor"; descriptor: AxDescriptorMatch } | { type: "tool_result"; jsonpath: string } | { type: "literal"; value: JsonValue }
/**
 * User-selected app for CDP during walkthrough.
 */
export type CdpAppConfig = { name: string; 
/**
 * Path to the app binary (from file picker). None for already-running apps.
 */
binary_path: string | null; app_kind: AppKind }
export type ChromeProfile = { id: string; name: string; google_email: string | null }
export type ClearAgentConversationRequest = { project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
/**
 * Structured error type for Tauri IPC commands.
 */
export type CommandError = { kind: ErrorKind; message: string }
/**
 * Wire form for `resolve_completion_disagreement`. Mirrors
 * `DisagreementResolutionAction` but derives `specta::Type` so the
 * TypeScript binding picks it up.
 */
export type CompletionDisagreementActionWire = "confirm" | "cancel"
export type ConfirmSkillProposalRequest = { skill_id: string; version: number; accepted_proposal: SkillRefinementProposal; project_path: string | null; project_name: string; project_id: string; run_id: string | null; store_traces: boolean }
export type ConfirmableTool = { name: string; description: string }
export type DeleteSkillRequest = { skill_id: string; version: number; scope: SkillScope; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
/**
 * A running app detected as Electron or Chrome, returned to the frontend for CDP selection.
 */
export type DetectedCdpApp = { name: string; pid: number; app_kind: AppKind }
export type EndpointConfig = { base_url: string; model: string; api_key: string | null }
export type ErrorKind = "Validation" | "Io" | "Mcp" | "AlreadyRunning" | "Internal"
export type ExecutionMode = "Test" | "Run"
/**
 * Skills-layer mirror of `agent::types::WorldModelDiff` (same
 * `changed_fields: Vec<String>` shape). Owned by this module so the
 * `Skill` value round-trips through YAML / JSON without forcing
 * `Deserialize` onto the runtime diff type. The extractor (Phase 3)
 * converts from `WorldModelDiff` at the boundary.
 */
export type ExpectedWorldModelDelta = { changed_fields: string[] }
export type ForkSkillRequest = { skill_id: string; version: number; new_name: string; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
export type HydratedMilestoneKind = "subgoal_completed" | "recovery_succeeded"
export type HydratedPhase = "exploring" | "executing" | "recovering"
export type HydratedRunTrace = { run_id: string; phase: HydratedPhase; active_subgoal: string; steps: HydratedTraceStep[]; world_model_deltas: HydratedWorldModelDelta[]; milestones: HydratedTraceMilestone[]; terminal_frame: HydratedTerminalFrame | null }
export type HydratedTerminalFrame = { kind: HydratedTerminalKind; detail: string }
export type HydratedTerminalKind = "complete" | "stopped" | "error" | "disagreement_cancelled"
export type HydratedTraceMilestone = { step_index: number; kind: HydratedMilestoneKind; text: string }
export type HydratedTraceStep = { step_index: number; tool_name: string; phase: HydratedPhase; body: string; failed: boolean }
export type HydratedWorldModelDelta = { step_index: number; changed_fields: string[] }
export type Hypothesis = { text: string; recorded_at_step: number; refuted: boolean }
export type ImportedAsset = { relative_path: string; absolute_path: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ListSkillsRequest = { scope: SkillScope; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
export type LoadAgentChatRequest = { project_path: string | null; project_name: string; project_id: string }
export type LoadLatestRunTraceRequest = { project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
/**
 * Request for [`load_skill_full`] — resolves the full [`Skill`] value
 * (including `sections` and `body`) for a given skill id. The panel
 * sidebar already holds `SkillSummary`; this is called once, on
 * selection, to hydrate the detail view.
 */
export type LoadSkillFullRequest = { skill_id: string; version: number; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
export type LoopPredicate = { type: "world_model_delta"; expr: string } | { type: "step_count_reached"; count: number }
/**
 * Wire-format `MarkdownReplacement` for Tauri IPC (mirrors the engine type
 * with serde/specta derives).
 */
export type MarkdownReplacementDto = { old_text: string; new_text: string }
export type Milestone = { subgoal_id: SubgoalId; text: string; summary: string; pushed_at_step: number; completed_at_step: number }
export type MouseButton = "Left" | "Right" | "Center"
export type NodeRename = { node_id: string; new_name: string }
export type OutcomePredicate = { type: "subgoal_completed"; post_state_world_model_signature: string | null }
export type OutputDeclaration = { name: string; type_tag: string; from: BindingRef }
export type ParameterSlot = { name: string; type_tag: string; description: string | null; default: JsonValue | null; enum_values: string[] | null }
export type PermissionActionWire = "allow" | "ask" | "deny"
/**
 * Wire form of the permission policy the UI ships with every `run_agent`.
 * `tools` is the per-tool override map from the existing 2-tier UI (ask
 * / allow). It is mapped into `PermissionRule`s with the tool name as a
 * literal pattern so the Rust side only needs one evaluator.
 */
export type PermissionPolicyWire = { rules?: PermissionRuleWire[]; allow_all?: boolean; require_confirm_destructive?: boolean; 
/**
 * Per-tool overrides: `{ "click": "allow" }`. Merged into the rule
 * list as literal-pattern rules before the evaluator runs.
 */
per_tool?: Partial<{ [key in string]: PermissionActionWire }> }
/**
 * Wire form of a single permission rule. Mirrors
 * `clickweave_engine::agent::PermissionRule` but with a `specta::Type`
 * derive so the TypeScript bindings pick it up.
 */
export type PermissionRuleWire = { tool_pattern: string; args_pattern: string | null; action: PermissionActionWire }
/**
 * Harness-inferred phase of the agent run. Never authored by the LLM (D5).
 */
export type Phase = 
/**
 * No active subgoal; the agent is deciding what to pursue.
 */
"exploring" | 
/**
 * Active subgoal and recent steps are succeeding.
 */
"executing" | 
/**
 * Consecutive errors or an `agent_replan` this step.
 */
"recovering"
/**
 * Wire form of a prior-turn entry (matches
 * `clickweave_engine::agent::PriorTurn` with string UUIDs for JSON).
 */
export type PriorTurnWire = { goal: string; summary: string; run_id: string }
export type ProjectData = { path: string; manifest: ProjectManifest }
/**
 * Slim project envelope persisted to `<project>.json`.
 */
export type ProjectManifest = { id: string; name: string; intent?: string | null; schema_version: number }
export type PromoteSkillToGlobalRequest = { skill_id: string; version: number; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
export type ProvenanceEntry = { run_id: string; step_index: number; completed_at: string; workflow_hash: string }
export type PruneSkillLineageRequest = { project_path: string | null; project_name: string; project_id: string; node_ids: string[]; store_traces: boolean }
export type ReadArtifactQuery = { project_path: string | null; project_id: string; project_name: string; skill_id: string; run_id: string; artifact_path: string }
export type RejectSkillProposalRequest = { skill_id: string; version: number; project_path: string | null; project_name: string; project_id: string; store_traces: boolean }
/**
 * Wire-format `ReplaySidecarMutation` for Tauri IPC.
 */
export type ReplaySidecarMutationDto = { type: "clear_signals"; step_id: string } | { type: "append_section_history"; retired: string; split_into: string[]; at_version: number } | { type: "delete_step_bundle"; step_id: string } | { type: "update_requires_approval"; step_id: string; value: boolean | null }
/**
 * Request body for `resume_skill_from_failure`.
 * Inherits all fields from `RunSkillRequest` and adds the section to resume from.
 */
export type ResumeSkillFromFailureRequest = { project_path: string | null; project_id: string; project_name: string; skill_id: string; variables?: Partial<{ [key in string]: JsonValue }>; agent: EndpointConfig; fast: EndpointConfig | null; supervisor: EndpointConfig | null; execution_mode: ExecutionMode; supervision_delay_ms?: number; store_traces: boolean | null; 
/**
 * The section ID to resume from. All sections before this section are skipped.
 */
from_section_id: string }
export type RunEventsQuery = { project_path: string | null; project_id: string; project_name: string; skill_id: string; run_id: string }
/**
 * IPC payload for `run_skill` (D33). Replaces the legacy `RunRequest`
 * which carried a full `Workflow` graph. Every field on the legacy
 * request that fed downstream privacy / supervision gates is preserved
 * here so Phase 1.L acceptance still passes.
 */
export type RunSkillRequest = { 
/**
 * Saved-project workspace path. `None` for unsaved projects — in that
 * case `RunStorage::new_app_data(app_data, &project_name, project_id)`
 * resolves the storage from the manifest identity below.
 */
project_path: string | null; 
/**
 * Project identity carried forward from `ProjectManifest` (D33).
 * Required for unsaved-project skill resolution and for run-trace
 * storage paths.
 */
project_id: string; project_name: string; skill_id: string; variables?: Partial<{ [key in string]: JsonValue }>; agent: EndpointConfig; fast: EndpointConfig | null; 
/**
 * Optional supervisor model for Test mode.
 */
supervisor: EndpointConfig | null; execution_mode: ExecutionMode; supervision_delay_ms?: number; 
/**
 * Privacy kill switch — `Some(false)` disables run/skill artifact
 * persistence (D31). `None` falls back to settings.
 */
store_traces: boolean | null }
export type RunStatus = "Ok" | "Failed" | "Stopped" | "Cancelled"
export type RunsQuery = { project_path: string | null; project_id: string; project_name: string; 
/**
 * Skill identifier (D27/D28). Run records live under
 * `<skills>/<skill_id>/runs/`.
 */
skill_id: string; 
/**
 * When `Some`, narrow the result to a single run record. When
 * `None`, the command returns every run for the skill (sorted
 * oldest-first).
 */
run_id?: string | null; 
/**
 * Optional section filter retained on the wire so the UI can
 * request a section-scoped slice once the per-section run timeline
 * lands. Ignored by the Phase 1.D loader.
 */
section_id?: string | null }
export type SaveAgentChatRequest = { project_path: string | null; project_name: string; project_id: string; chat: AgentChat; store_traces: boolean }
export type SaveRunAsSkillRequest = { project_path: string | null; project_name: string; project_id: string; name: string; goal: string; steps: AgentStepWire[]; store_traces: boolean }
export type SaveWalkthroughAsSkillRequest = { session_id: string; project_path: string | null; project_name: string; project_id: string; name: string; store_traces: boolean }
/**
 * Screenshot coordinate metadata for mapping screen coordinates to image pixels.
 * 
 * Given a screen coordinate `(sx, sy)`, the image pixel coordinate is:
 * `px = (sx - origin_x) * scale`, `py = (sy - origin_y) * scale`
 */
export type ScreenshotMeta = { origin_x: number; origin_y: number; scale: number }
/**
 * Per-section run outcome carried inside a [`SkillRun`].
 * 
 * Sections are addressed by their `<!-- section: <id> -->` markers in
 * `SKILL.md`. Outcomes drive the per-section state pill on the run
 * timeline and the fidelity dot aggregation in Phase 2.
 */
export type SectionOutcome = 
/**
 * Section has not started yet.
 */
"pending" | 
/**
 * Section is currently executing.
 */
"running" | 
/**
 * Section completed without intervention.
 */
"succeeded" | 
/**
 * Section completed but at least one repair iteration was needed.
 */
"repaired" | 
/**
 * Section failed and the run halted (or moved on after the user
 * chose to skip — the per-section status is still `Failed`).
 */
"failed" | 
/**
 * Section was deliberately skipped (e.g. operator chose Skip on a
 * supervision pause).
 */
"skipped"
export type Skill = { id: string; version: number; state: SkillState; scope: SkillScope; name: string; description: string; tags: string[]; subgoal_text: string; subgoal_signature: SubgoalSignature; applicability: ApplicabilityHints; parameter_schema: ParameterSlot[]; action_sketch: ActionSketchStep[]; outputs: OutputDeclaration[]; outcome_predicate: OutcomePredicate; provenance: ProvenanceEntry[]; stats: SkillStats; edited_by_user: boolean; created_at: string; updated_at: string; produced_node_ids: string[]; body: string; 
/**
 * Parsed marker grammar — populated by the new parser. Empty for
 * in-memory skills built directly from `action_sketch`.
 */
schema_version?: number; variables?: SkillFrontmatterVariable[]; sections?: SkillSection[] }
export type SkillFrontmatterVariable = { name: string; type: string; description: string | null; default: JsonValue | null }
/**
 * Wire-format `SkillFrontmatterVariable` addition for Tauri IPC.
 */
export type SkillFrontmatterVariableDto = { name: string; type: string; description: string | null; default: JsonValue | null }
/**
 * Primitive discriminant for the diff preview label.
 */
export type SkillPatchPrimitiveDto = "rebind" | "reorder" | "promote" | "free_form_prose"
export type SkillRefinementProposal = { parameter_schema: ParameterSlot[]; binding_corrections: BindingCorrection[]; description: string; name_suggestion: string | null }
/**
 * Persisted record of a single skill execution.
 * 
 * One JSON document per run is written at
 * `<skills>/<skill_id>/runs/<run_id>.json`; trace events stream to
 * `<skills>/<skill_id>/runs/<run_id>/events.jsonl` under the same
 * directory.
 */
export type SkillRun = { run_id: string; 
/**
 * Skill identifier (matches the directory name on disk).
 */
skill_id: string; started_at: string; finished_at: string | null; status: RunStatus; duration_ms: number | null; 
/**
 * Per-section outcomes keyed by section ID
 * (`<!-- section: <id> -->` marker).
 */
per_section_outcome?: Partial<{ [key in string]: SectionOutcome }>; repair_count?: number }
export type SkillScope = "project_local" | "global"
/**
 * Per-section view of a parsed skill body. Populated by
 * `parser::parse_skill_md`; `body_range` is a UTF-16 code-unit range
 * into the raw markdown body string (start..end of the section's
 * prose after the heading, measured in JS-compatible UTF-16 units so
 * the frontend can use `body.slice(start, end)` directly).
 */
export type SkillSection = { id: string; heading: string; level: number; step_ids: string[]; body_range: [number, number] }
export type SkillState = "draft" | "confirmed" | "promoted"
export type SkillStats = { occurrence_count: number; success_rate: number; last_seen_at: string | null; last_invoked_at: string | null }
/**
 * Lightweight projection of [`Skill`] for the Skills panel listing.
 * The full canvas + frontmatter are loaded on demand when the user
 * opens a detail view, so the panel index stays small.
 */
export type SkillSummary = { id: string; version: number; name: string; description: string; state: SkillState; scope: SkillScope; tags: string[]; parameter_schema: ParameterSlot[]; applicability: ApplicabilityHints; action_sketch: ActionSketchStep[]; proposal: SkillRefinementProposal | null; occurrence_count: number; success_rate: number; edited_by_user: boolean }
export type Subgoal = { id: SubgoalId; text: string; pushed_at_step: number; parent: SubgoalId | null }
export type SubgoalId = string
export type SubgoalSignature = string
export type TargetCandidate = { type: "AccessibilityLabel"; label: string; role: string | null } | 
/**
 * Label identified by a vision language model from a screenshot crop.
 */
{ type: "VlmLabel"; label: string } | { type: "OcrText"; text: string } | { type: "ImageCrop"; path: string; image_b64: string } | { type: "Coordinates"; x: number; y: number } | 
/**
 * Element captured via Chrome DevTools Protocol click listener.
 */
{ type: "CdpElement"; name: string; role: string | null; href: string | null; parent_role: string | null; parent_name: string | null } | 
/**
 * macOS accessibility element reached via the native AX tree — the
 * target descriptor for `ax_click` / `ax_set_value` / `ax_select`.
 * Populated only when the role is actionable (button, text field,
 * menu item, row, etc.) and the app exposes an AX tree. Replay
 * re-resolves this to a fresh uid via `take_ax_snapshot` at
 * execution time, so no generation-tagged uid is carried on the
 * candidate.
 */
{ type: "AxElement"; role: string; name: string; parent_name?: string | null } | 
/**
 * macOS window control button (close, minimize, maximize).
 * Resolved at execution time to a window-relative click.
 */
{ type: "WindowControl"; action: WindowControlAction }
export type TargetOverride = { node_id: string; chosen_candidate_index: number }
export type TaskState = { goal: string; subgoal_stack: Subgoal[]; watch_slots: WatchSlot[]; hypotheses: Hypothesis[]; phase: Phase; milestones: Milestone[] }
export type TraceEvent = { timestamp: number; event_type: TraceEventKind; payload: JsonValue }
/**
 * The canonical set of trace event kinds emitted by the executor.
 * 
 * Serialized as snake_case strings so the on-disk shape matches the literal
 * event-type strings that the engine has emitted historically. Legacy
 * `events.jsonl` files therefore load unchanged. Unknown strings deserialize
 * as [`TraceEventKind::Unknown`] so forward-compatible additions don't break
 * old readers.
 */
export type TraceEventKind = "node_started" | "tool_call" | "tool_result" | "step_completed" | "step_failed" | "branch_evaluated" | "loop_iteration" | "target_resolved" | "action_verification" | "ambiguity_resolved" | "element_resolved" | "match_disambiguated" | "app_resolved" | "cdp_connected" | "cdp_click" | "cdp_hover" | "cdp_fill" | "ax_click" | "ax_set_value" | "ax_select" | "vision_summary" | "variable_set" | "retry" | "supervision_retry" | 
/**
 * Forward-compatibility catch-all for event kinds that aren't in this
 * enum yet. `#[serde(other)]` parses any unknown string into `Unknown`.
 */
"unknown"
export type VariablePromotion = { node_id: string; variable_name: string }
export type WalkthroughAction = { id: string; kind: WalkthroughActionKind; app_name: string | null; window_title: string | null; target_candidates: TargetCandidate[]; artifact_paths: string[]; source_event_ids: string[]; confidence: ActionConfidence; warnings: string[]; 
/**
 * Screenshot coordinate metadata for VLM click target resolution.
 */
screenshot_meta?: ScreenshotMeta | null; 
/**
 * Whether this action is a candidate (e.g. detected hover) that needs
 * explicit user confirmation before inclusion in the draft.
 */
candidate?: boolean }
export type WalkthroughActionKind = { type: "LaunchApp"; app_name: string; app_kind: AppKind } | { type: "FocusWindow"; app_name: string; window_title: string | null; app_kind: AppKind } | { type: "Click"; x: number; y: number; button: MouseButton; click_count: number } | { type: "TypeText"; text: string } | { type: "PressKey"; key: string; modifiers: string[] } | { type: "Scroll"; delta_y: number } | { type: "Hover"; x: number; y: number; dwell_ms: number }
export type WalkthroughAnnotations = { deleted_node_ids: string[]; renamed_nodes: NodeRename[]; target_overrides: TargetOverride[]; variable_promotions: VariablePromotion[] }
export type WalkthroughDraftResponse = { session_id: string; actions: WalkthroughAction[]; warnings: string[] }
export type WatchSlot = { name: WatchSlotName; note: string; set_at_step: number }
export type WatchSlotName = "pending_modal" | "pending_auth" | "pending_focus_shift"
/**
 * macOS window control button (traffic light) actions.
 * 
 * At execution time these are resolved to window-relative clicks by
 * querying the focused window's position and applying a fixed pixel offset.
 * This is more reliable than keyboard shortcuts — e.g. Cmd+W closes a tab
 * in tabbed apps, not the window.
 */
export type WindowControlAction = "Close" | "Minimize" | "Maximize" | 
/**
 * Green button in "zoom" mode — resizes/maximizes the window without
 * entering full screen. Same physical button as Maximize but different
 * macOS subrole (`AXZoomButton` vs `AXFullScreenButton`).
 */
"Zoom"
/**
 * Per-step diff of the harness-owned `WorldModel`. Carries the field
 * names whose freshness-wrapped value changed during the current
 * step's `observe` pass (D17). Intentionally minimal — the frontend
 * only needs a re-render hint, not the full snapshot. Field order
 * matches `WorldModel`'s definition.
 */
export type WorldModelDiff = { 
/**
 * Names of `WorldModel` fields whose value changed this step.
 * Stable field names: `focused_app`, `window_list`, `cdp_page`,
 * `elements`, `modal_present`, `dialog_present`,
 * `last_screenshot`, `last_native_ax_snapshot`, `uncertainty`.
 */
changed_fields: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
